language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose up --build

after_script:
  - curl localhost:4200
  - curl localhost:3000
  - curl localhost:27017
  - docker-compose down
